on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at 12am
  push: # Add this trigger to run on new push events
    branches:
      - main

env:
  DISCORD_URL: ${{ secrets.DISCORD_URL }}

jobs:
  postman-test:
    name: Run Newman Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run Newman tests
        run: node report.js ${{ secrets.DISCORD_URL }}

      - name: Upload report.html to repository #Uploading Html File to Github Repo
        uses: actions/upload-artifact@v2
        with:
          name: Newman Test Report
          path: ./Reports/report.html
